"""empty message

Revision ID: 2ecb8b399c09
Revises: cdb33a10e34a
Create Date: 2025-12-10 17:01:35.360733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecb8b399c09'
down_revision = 'cdb33a10e34a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reflexe_link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('reflexe_link')

    # ### end Alembic commands ###
