"""empty message

Revision ID: 63075c566364
Revises: 53fffda885cf
Create Date: 2024-10-26 18:56:44.421634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63075c566364'
down_revision = '53fffda885cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perm_program_edit', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('perm_shop', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('perm_shop')
        batch_op.drop_column('perm_program_edit')

    # ### end Alembic commands ###
