"""empty message

Revision ID: 653a0ce18f63
Revises: 5bdd25deccfc
Create Date: 2024-11-23 11:42:40.710004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653a0ce18f63'
down_revision = '5bdd25deccfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1800), nullable=True))
        batch_op.add_column(sa.Column('picture_filename', sa.String(length=20), nullable=False, server_default="default.png"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('picture_filename')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
