"""empty message

Revision ID: 9e081ca4c58b
Revises: 8062a506b95d
Create Date: 2024-12-05 19:52:26.152688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e081ca4c58b'
down_revision = '8062a506b95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perm_fotogalerie', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('perm_fotogalerie')

    # ### end Alembic commands ###
