"""empty message

Revision ID: b8622aa790fd
Revises: 653a0ce18f63
Create Date: 2024-12-03 19:24:25.104942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8622aa790fd'
down_revision = '653a0ce18f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beseda', schema=None) as batch_op:
        batch_op.drop_column('recommended')

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('recommended')

    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.drop_column('recommended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    with op.batch_alter_table('beseda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
