"""empty message

Revision ID: cdb33a10e34a
Revises: f0c0c1763e5c
Create Date: 2024-12-10 22:24:14.228775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb33a10e34a'
down_revision = 'f0c0c1763e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
