"""empty message

Revision ID: f35b5ed1e72d
Revises: db8e645547a2
Create Date: 2024-03-16 11:38:33.211677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35b5ed1e72d'
down_revision = 'db8e645547a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beseda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vg', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recommended', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vg', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recommended', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vg', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('recommended', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop', schema=None) as batch_op:
        batch_op.drop_column('recommended')
        batch_op.drop_column('vg')

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('recommended')
        batch_op.drop_column('vg')

    with op.batch_alter_table('beseda', schema=None) as batch_op:
        batch_op.drop_column('recommended')
        batch_op.drop_column('vg')

    # ### end Alembic commands ###
